-- Drop tables if exist
DROP TABLE transactions;
DROP TABLE budgets;

-- Budgets Table
CREATE TABLE BUDGETS(
   BUDGET_NAME TEXT PRIMARY KEY NOT NULL,
   BUDGET_NAME_HTML_ID TEXT NOT NULL,
   BUDGET_AMOUNT MONEY NOT NULL,
   BUDGET_AMOUNT_USED MONEY NOT NULL,
   BUDGET_AMOUNT_LEFT MONEY NOT NULL
);

-- Transactions table
CREATE TABLE TRANSACTIONS(
   ID SERIAL PRIMARY KEY,
   MERCHANT_NAME TEXT NOT NULL,
   PURCHASE_AMOUNT MONEY NOT NULL,
   BUDGET_NAME TEXT REFERENCES budgets(budget_name),
   NOTES TEXT
);
